[[redirects]]
  from = "http://www.torontopubliclibra.com/*"
  to = "https://www.danateagle.com/tpl/:splat"
  status = 301
  force = true

  [[redirects]]
  from = "https://www.torontopubliclibra.com/*"
  to = "https://www.danateagle.com/tpl/:splat"
  status = 301
  force = true
  
  [[redirects]]
  from = "http://torontopubliclibra.com/*"
  to = "https://www.danateagle.com/tpl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://torontopubliclibra.com/*"
  to = "https://www.danateagle.com/tpl/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true