[[redirects]]
  from = "http://www.torontopubliclibra.com/"
  to = "https://www.danateagle.com/tpl/"
  status = 200
  force = true

[[redirects]]
  from = "https://www.torontopubliclibra.com/"
  to = "https://www.danateagle.com/tpl/"
  status = 200
  force = true

[[redirects]]
  from = "http://www.torontopubliclibra.com/*"
  to = "https://www.danateagle.com/tpl/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.torontopubliclibra.com/*"
  to = "https://www.danateagle.com/tpl/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "http://torontopubliclibra.com/*"
  to = "https://www.danateagle.com/tpl/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://torontopubliclibra.com/*"
  to = "https://www.danateagle.com/tpl/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/tpl/*"
  to = "/tpl/404.html"
  status = 404

[[redirects]]
  from = "/rustprop/*"
  to = "/tpl/404.html"
  status = 404