[[redirects]]
  from = "http://www.torontopubliclibra.com/"
  to = "https://www.danateagle.com/tpl/"
  status = 200
  force = true

[[redirects]]
  from = "https://www.torontopubliclibra.com/"
  to = "https://www.danateagle.com/tpl/"
  status = 200
  force = true

[[redirects]]
  from = "http://www.torontopubliclibra.com/*"
  to = "https://www.danateagle.com/tpl/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.torontopubliclibra.com/*"
  to = "https://www.danateagle.com/tpl/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "http://torontopubliclibra.com/*"
  to = "https://www.danateagle.com/tpl/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://torontopubliclibra.com/*"
  to = "https://www.danateagle.com/tpl/:splat"
  status = 200
  force = true

[[redirects]]
  from = "http://www.rustprop.org/"
  to = "https://www.danateagle.com/rustprop/"
  status = 200
  force = true

[[redirects]]
  from = "https://www.rustprop.org/"
  to = "https://www.danateagle.com/rustprop/"
  status = 200
  force = true

[[redirects]]
  from = "http://www.rustprop.org/*"
  to = "https://www.danateagle.com/rustprop/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://www.rustprop.org/*"
  to = "https://www.danateagle.com/rustprop/:splat"
  status = 200
  force = true
  
[[redirects]]
  from = "http://rustprop.org/*"
  to = "https://www.danateagle.com/rustprop/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://rustprop.org/*"
  to = "https://www.danateagle.com/rustprop/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/tpl/*"
  to = "/tpl/404.html"
  status = 404

[[redirects]]
  from = "/rustprop/*"
  to = "/tpl/404.html"
  status = 404